-- Travel data is accessible only to explicitly provisioned members.
create table public.profiles (id uuid primary key references auth.users on delete cascade, username text unique not null check(username ~ '^[a-zA-Z0-9_-]{3,32}$'), display_name text not null);
alter table public.profiles enable row level security;
create table public.trips (id uuid primary key default gen_random_uuid(), title text not null, start_date date not null, end_date date not null, timezone text not null default 'Asia/Tokyo', currency text not null default 'JPY', check(end_date >= start_date));
create table public.trip_members (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, user_id uuid not null references profiles, role text not null check(role in ('OWNER','EDITOR','VIEWER')), slot text not null check(slot in ('USER_A','USER_B')), unique(trip_id,user_id), unique(trip_id,slot), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.trip_days (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, date date not null, day_number integer not null check(day_number between 1 and 6), title text not null, hotel_name text, estimated_cost_min_yen integer check(estimated_cost_min_yen>=0), estimated_cost_max_yen integer check(estimated_cost_max_yen>=estimated_cost_min_yen), unique(trip_id,date), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.places (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, google_place_id text, custom_name text not null, category text not null default 'OTHER', memo text not null default '', unique(trip_id,google_place_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.schedule_items (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, date date not null, type text not null default 'OTHER', title text not null, time_label text not null default '', start_time time, end_time time, place_id uuid, description text not null default '', status text not null default 'planned' check(status in ('planned','confirmed','completed','skipped')), sort_order integer not null default 0, is_fixed boolean not null default false, estimated_cost_yen integer check(estimated_cost_yen>=0), note text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.reservations (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, type text not null default 'OTHER', title text not null, provider text, reservation_number text, booker_name text, start_at timestamptz, end_at timestamptz, website_url text, booking_url text, confirmation_url text, contact_phone text, contact_email text, status text not null default 'PLANNED' check(status in ('PLANNED','BOOKED','CONFIRMED','USED','CANCELLED')), seat_number text, carriage_number text, flight_number text, room_info text, ticket_method text, qr_note text, insurance_number text, note text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.transport_segments (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, date date not null, schedule_item_id uuid, origin_place_id uuid, destination_place_id uuid, origin_name text not null, destination_name text not null, departure_time time, arrival_time time, time_label text not null default '', transport_type text not null, route_name text not null default '', operator text, boarding_point text, alighting_point text, estimated_duration_minutes integer check(estimated_duration_minutes>=0), estimated_cost_min_yen integer check(estimated_cost_min_yen>=0), estimated_cost_max_yen integer check(estimated_cost_max_yen>=estimated_cost_min_yen), reservation_required boolean not null default false, reservation_id uuid, ticket_note text not null default '', preparation_note text not null default '', is_fixed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.meal_candidates (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, place_id uuid not null, meal_schedule_id uuid, memo text not null default '', priority integer not null default 0, tags text not null default '', favorite boolean not null default false, visited boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.packing_items (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, date date, schedule_item_id uuid, label text not null, category text not null default 'OTHER', owner text not null default 'SHARED' check(owner in ('USER_A','USER_B','SHARED')), checked boolean not null default false, required boolean not null default true, note text not null default '', sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.checklist_items (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, date date, schedule_item_id uuid, title text not null, description text not null default '', owner text not null default 'SHARED' check(owner in ('USER_A','USER_B','SHARED')), status text not null default 'TODO' check(status in ('TODO','DONE')), due_at timestamptz, priority integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.reservation_attachments (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, reservation_id uuid not null, file_name text not null, storage_path text not null unique, mime_type text not null check(mime_type in ('application/pdf','image/png','image/jpeg','image/webp')), size_bytes integer not null check(size_bytes between 1 and 10485760), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.reservation_schedule_items (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, reservation_id uuid not null, schedule_item_id uuid not null, unique(trip_id,reservation_id,schedule_item_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.budget_items (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, category text not null, title text not null, estimated_amount_yen integer not null check(estimated_amount_yen>=0), estimated_max_yen integer check(estimated_max_yen>=estimated_amount_yen), actual_amount_yen integer check(actual_amount_yen>=0), note text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.expenses (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, date date not null, category text not null, title text not null, amount integer not null check(amount>0), currency text not null default 'JPY' check(currency='JPY'), payer_user_id uuid not null, split_mode text not null default 'EQUAL' check(split_mode in ('EQUAL','USER_A_ONLY','USER_B_ONLY','CUSTOM')), share_a_yen integer not null check(share_a_yen>=0), share_b_yen integer not null check(share_b_yen>=0), place_id uuid, note text not null default '', check(share_a_yen+share_b_yen=amount), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.expense_splits (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, expense_id uuid not null, user_id uuid not null, amount_yen integer not null check(amount_yen>=0), unique(trip_id,expense_id,user_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.shopping_items (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, name text not null, category text not null default 'OTHER', target_place_id uuid, planned_budget_yen integer check(planned_budget_yen>=0), actual_cost_yen integer check(actual_cost_yen>=0), buyer text not null default 'SHARED' check(buyer in ('USER_A','USER_B','SHARED')), purchased boolean not null default false, note text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.emergency_contacts (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, category text not null default 'OTHER', title text not null, phone text, url text, note text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create table public.notes (id uuid primary key default gen_random_uuid(), trip_id uuid not null references public.trips on delete cascade, date date, schedule_item_id uuid, title text not null, body text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(trip_id,id));
create policy profile_read on public.profiles for select to authenticated using (id=auth.uid() or exists(select 1 from public.trip_members m join public.trip_members mine using(trip_id) where m.user_id=profiles.id and mine.user_id=auth.uid()));
create function public.is_member(t uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from trip_members where trip_id=t and user_id=auth.uid()) $$;
create function public.can_edit(t uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from trip_members where trip_id=t and user_id=auth.uid() and role in ('OWNER','EDITOR')) $$;
revoke all on function public.is_member(uuid),public.can_edit(uuid) from public;
grant execute on function public.is_member(uuid),public.can_edit(uuid) to authenticated;
alter table public.trip_members enable row level security;
create policy member_read on public.trip_members for select to authenticated using(public.is_member(trip_id));
alter table public.trips enable row level security;
create policy trip_read on public.trips for select to authenticated using(public.is_member(id));
create policy trip_update on public.trips for update to authenticated using(public.can_edit(id)) with check(public.can_edit(id));
create function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
alter table public.trip_days enable row level security;
create policy read_members on public.trip_days for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.trip_days for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.trip_days for each row execute function public.touch_updated_at();
create index on public.trip_days(trip_id);
alter table public.places enable row level security;
create policy read_members on public.places for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.places for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.places for each row execute function public.touch_updated_at();
create index on public.places(trip_id);
alter table public.schedule_items enable row level security;
create policy read_members on public.schedule_items for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.schedule_items for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.schedule_items for each row execute function public.touch_updated_at();
create index on public.schedule_items(trip_id);
alter table public.schedule_items add foreign key(trip_id,place_id) references public.places(trip_id,id);
alter table public.schedule_items add foreign key(trip_id,date) references public.trip_days(trip_id,date);
alter table public.reservations enable row level security;
create policy read_members on public.reservations for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.reservations for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.reservations for each row execute function public.touch_updated_at();
create index on public.reservations(trip_id);
alter table public.transport_segments enable row level security;
create policy read_members on public.transport_segments for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.transport_segments for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.transport_segments for each row execute function public.touch_updated_at();
create index on public.transport_segments(trip_id);
alter table public.transport_segments add foreign key(trip_id,origin_place_id) references public.places(trip_id,id);
alter table public.transport_segments add foreign key(trip_id,destination_place_id) references public.places(trip_id,id);
alter table public.transport_segments add foreign key(trip_id,schedule_item_id) references public.schedule_items(trip_id,id);
alter table public.transport_segments add foreign key(trip_id,reservation_id) references public.reservations(trip_id,id);
alter table public.transport_segments add foreign key(trip_id,date) references public.trip_days(trip_id,date);
alter table public.meal_candidates enable row level security;
create policy read_members on public.meal_candidates for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.meal_candidates for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.meal_candidates for each row execute function public.touch_updated_at();
create index on public.meal_candidates(trip_id);
alter table public.meal_candidates add foreign key(trip_id,place_id) references public.places(trip_id,id);
alter table public.meal_candidates add foreign key(trip_id,meal_schedule_id) references public.schedule_items(trip_id,id);
alter table public.packing_items enable row level security;
create policy read_members on public.packing_items for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.packing_items for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.packing_items for each row execute function public.touch_updated_at();
create index on public.packing_items(trip_id);
alter table public.packing_items add foreign key(trip_id,schedule_item_id) references public.schedule_items(trip_id,id);
alter table public.packing_items add foreign key(trip_id,date) references public.trip_days(trip_id,date);
alter table public.checklist_items enable row level security;
create policy read_members on public.checklist_items for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.checklist_items for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.checklist_items for each row execute function public.touch_updated_at();
create index on public.checklist_items(trip_id);
alter table public.checklist_items add foreign key(trip_id,schedule_item_id) references public.schedule_items(trip_id,id);
alter table public.checklist_items add foreign key(trip_id,date) references public.trip_days(trip_id,date);
alter table public.reservation_attachments enable row level security;
create policy read_members on public.reservation_attachments for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.reservation_attachments for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.reservation_attachments for each row execute function public.touch_updated_at();
create index on public.reservation_attachments(trip_id);
alter table public.reservation_attachments add foreign key(trip_id,reservation_id) references public.reservations(trip_id,id);
alter table public.reservation_schedule_items enable row level security;
create policy read_members on public.reservation_schedule_items for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.reservation_schedule_items for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.reservation_schedule_items for each row execute function public.touch_updated_at();
create index on public.reservation_schedule_items(trip_id);
alter table public.reservation_schedule_items add foreign key(trip_id,schedule_item_id) references public.schedule_items(trip_id,id);
alter table public.reservation_schedule_items add foreign key(trip_id,reservation_id) references public.reservations(trip_id,id);
alter table public.budget_items enable row level security;
create policy read_members on public.budget_items for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.budget_items for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.budget_items for each row execute function public.touch_updated_at();
create index on public.budget_items(trip_id);
alter table public.expenses enable row level security;
create policy read_members on public.expenses for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.expenses for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.expenses for each row execute function public.touch_updated_at();
create index on public.expenses(trip_id);
alter table public.expenses add foreign key(trip_id,place_id) references public.places(trip_id,id);
alter table public.expenses add foreign key(trip_id,date) references public.trip_days(trip_id,date);
alter table public.expenses add foreign key(trip_id,payer_user_id) references public.trip_members(trip_id,user_id);
alter table public.expense_splits enable row level security;
create policy read_members on public.expense_splits for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.expense_splits for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.expense_splits for each row execute function public.touch_updated_at();
create index on public.expense_splits(trip_id);
alter table public.expense_splits add foreign key(trip_id,expense_id) references public.expenses(trip_id,id);
alter table public.expense_splits add foreign key(trip_id,user_id) references public.trip_members(trip_id,user_id);
alter table public.shopping_items enable row level security;
create policy read_members on public.shopping_items for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.shopping_items for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.shopping_items for each row execute function public.touch_updated_at();
create index on public.shopping_items(trip_id);
alter table public.shopping_items add foreign key(trip_id,target_place_id) references public.places(trip_id,id);
alter table public.emergency_contacts enable row level security;
create policy read_members on public.emergency_contacts for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.emergency_contacts for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.emergency_contacts for each row execute function public.touch_updated_at();
create index on public.emergency_contacts(trip_id);
alter table public.notes enable row level security;
create policy read_members on public.notes for select to authenticated using(public.is_member(trip_id));
create policy edit_members on public.notes for all to authenticated using(public.can_edit(trip_id)) with check(public.can_edit(trip_id));
create trigger touch before update on public.notes for each row execute function public.touch_updated_at();
create index on public.notes(trip_id);
alter table public.notes add foreign key(trip_id,schedule_item_id) references public.schedule_items(trip_id,id);
alter table public.notes add foreign key(trip_id,date) references public.trip_days(trip_id,date);
create unique index one_visited_meal on public.meal_candidates(trip_id,meal_schedule_id) where visited and meal_schedule_id is not null;
create function public.validate_scope() returns trigger language plpgsql set search_path=public,pg_temp as $$
begin
 if new.schedule_item_id is not null and not exists(select 1 from schedule_items where id=new.schedule_item_id and trip_id=new.trip_id and (new.date is null or date=new.date)) then raise exception 'Schedule date mismatch'; end if;
 return new;
end $$;
create trigger packing_scope before insert or update on public.packing_items for each row execute function public.validate_scope();
create trigger checklist_scope before insert or update on public.checklist_items for each row execute function public.validate_scope();
create function public.validate_meal() returns trigger language plpgsql set search_path=public,pg_temp as $$ begin
 if new.meal_schedule_id is not null and not exists(select 1 from schedule_items where id=new.meal_schedule_id and trip_id=new.trip_id and type='MEAL') then raise exception 'Meal schedule required'; end if; return new; end $$;
create trigger meal_scope before insert or update on public.meal_candidates for each row execute function public.validate_meal();
-- Derived splits always follow the expense, including updates and deletes.
create function public.sync_splits() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ begin
 delete from expense_splits where expense_id=new.id;
 insert into expense_splits(trip_id,expense_id,user_id,amount_yen) select new.trip_id,new.id,user_id,case slot when 'USER_A' then new.share_a_yen else new.share_b_yen end from trip_members where trip_id=new.trip_id;
 return new; end $$;
alter table public.expense_splits drop constraint expense_splits_trip_id_expense_id_fkey;
alter table public.expense_splits add foreign key(trip_id,expense_id) references public.expenses(trip_id,id) on delete cascade;
create trigger expense_splits_sync after insert or update on public.expenses for each row execute function public.sync_splits();
drop policy edit_members on public.expense_splits;
revoke all on function public.sync_splits() from public;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('reservation-files','reservation-files',false,10485760,array['application/pdf','image/png','image/jpeg','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy private_read on storage.objects for select to authenticated using(bucket_id='reservation-files' and exists(select 1 from public.trip_members where trip_id::text=(storage.foldername(name))[1] and user_id=auth.uid()));
create policy private_insert on storage.objects for insert to authenticated with check(bucket_id='reservation-files' and exists(select 1 from public.trip_members where trip_id::text=(storage.foldername(name))[1] and user_id=auth.uid() and role in ('OWNER','EDITOR')));
create policy private_delete on storage.objects for delete to authenticated using(bucket_id='reservation-files' and exists(select 1 from public.trip_members where trip_id::text=(storage.foldername(name))[1] and user_id=auth.uid() and role in ('OWNER','EDITOR')));
alter publication supabase_realtime add table public.trip_days;
alter publication supabase_realtime add table public.places;
alter publication supabase_realtime add table public.schedule_items;
alter publication supabase_realtime add table public.reservations;
alter publication supabase_realtime add table public.transport_segments;
alter publication supabase_realtime add table public.meal_candidates;
alter publication supabase_realtime add table public.packing_items;
alter publication supabase_realtime add table public.checklist_items;
alter publication supabase_realtime add table public.reservation_attachments;
alter publication supabase_realtime add table public.reservation_schedule_items;
alter publication supabase_realtime add table public.budget_items;
alter publication supabase_realtime add table public.expenses;
alter publication supabase_realtime add table public.expense_splits;
alter publication supabase_realtime add table public.shopping_items;
alter publication supabase_realtime add table public.emergency_contacts;
alter publication supabase_realtime add table public.notes;
